### ISSUE TITLE
[INIT] Issue, PR 템플릿, pre-commit 설정 등..(프로젝트 초기 설정)

### ISSUE THREAD

**Issue by junhanjeong** [boostcampaitech7/level2-mrc-nlp-03#2]
## Background
- 프로젝트 시작을 위해 Issue 템플릿, PR 템플릿, Pre-commit 설정을 합니다.
- .gitignore을 설정하여 불필요한 파일의 커밋을 방지합니다.
- 프로젝트 초기이므로 바로 main브랜치에 커밋하려합니다.

## Todo
- [x] Issue 템플릿 (feature_request, bug_report) 만들기
- [x] PR 템플릿 만들기
- [x] Pre-commit (black, isort 모듈) 설정하기
- [x] .gitignore 작성
- [x] README.md 작성
